### ISSUE TITLE
Why hasn't the data set been accessible lately？？？

### ISSUE THREAD

**Issue by nightbreezecool** [lichengunc/refer#22]
Why hasn't the data set been accessible lately？？？

**Comment by hydrochloricacid** [comment]
I use this link to download the data:
https://web.archive.org/web/20220413011817/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refclef.zip
https://web.archive.org/web/20220413011718/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco.zip
https://web.archive.org/web/20220413011656/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco+.zip
https://web.archive.org/web/20220413012904/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcocog.zip

**Comment by nightbreezecool** [comment]
@hydrochloricacid thanks a lot!
